version: '3'

services:
  caddy_server:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine

    ports:
      - 80:80
      - 443:443
    networks:
      - controller
      - default
    environment:
      - CADDY_DOCKER_MODE=server
      - CADDY_CONTROLLER_NETWORK=10.200.200.0/24
    volumes:
      # this volume is needed to keep the certificates
      # otherwise, new ones will be re-issued upon restart
      - $PWD/data:/data
      - $PWD/config:/config
    labels:
      caddy_controlled_server:

  caddy_controller:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    networks:
      - controller
      - default
    environment:
      - CADDY_DOCKER_MODE=controller
      - CADDY_CONTROLLER_NETWORK=10.200.200.0/24
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  caddy_cloudflare_companion:
    image: whalemo/caddy-cloudflare-companion
    networks:
      - controller
    environment:
      - CADDY_VERSION=2
      - CF_EMAIL=email@example.com
      - CF_TOKEN=fbSx3dk3A3mJ6UukLQ7zRbo63H5UdsGSCqQnTvbJDgyQaTp

      - TARGET_DOMAIN=host.example.org
      - DOMAIN1=example.org
      - DOMAIN1_ZONE_ID=1234567890
      #- DOCKER_HOST=tcp://198.51.100.32:2376
      #- DOCKER_CERT_PATH=/docker-certs
      #- DOCKER_TLS_VERIFY=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
